#
###################################
# Site wide configuration
####################################
#
title:       "Marcos V. Pagelkopf Jr"
description: "Desenvolvedor PHP"
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Sao_Paulo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Marcos V. Pagelkopf Jr
  avatar: avatar.jpg
  job: "Desenvolvedor"
  bio: "Sou desenvolvedor, com foco em desenvolvimento para web.<br>Atualmente trabalho com PHP, AngularJS e Python."
  email: marcos@marcosvpj.com.br
  disqus-shortname:
  twitter:
  facebook:
  google:
    plus:
    analytics: UA-75789305-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: marcosvpj
  stackoverflow: 2271198/marcos
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
